name: Build and push base images
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ubuntu.yml
      - ubuntu/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ubuntu.yml
      - ubuntu/**
  schedule:
    - cron: "0 0 1 * *"
jobs:
  push:
    strategy:
      matrix:
        nvidia:
          - cuda: 11.2.2
            cudnn: 8
          - cuda: 11.5.2
            cudnn: 8
        ubuntu:
          - 20.04
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      CUDA_FULL_VERSION: "${{ matrix.nvidia.cuda }}"
      CUDNN_MAJOR_VERSION: "${{ matrix.nvidia.cudnn }}"
      UBUNTU_VERSION: "${{ matrix.ubuntu }}"
      BASE_IMAGE: "ghcr.io/${{ github.repository_owner }}/hailab/base:ubuntu${{ matrix.ubuntu }}-cuda${{ matrix.nvidia.cuda }}-cudnn${{ matrix.nvidia.cudnn }}-cn"
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build --build-arg CUDA_FULL_VERSION --build-arg CUDNN_MAJOR_VERSION --build-arg UBUNTU_VERSION --label "com.github.actions.run_id=${{ github.run_number }}" -t "${BASE_IMAGE}" .
        working-directory: ubuntu
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: docker push "${BASE_IMAGE}"
